### ISSUE TITLE
Functions (Expression) not working

### ISSUE THREAD

**Issue by moodstubos** [SaltechSystems/couchbase_lite#17]
the use of any function of "Functions"-class results in error message:

`Failed to handle method call
E/MethodChannel#com.saltechsystems.couchbase_lite/json(11267): java.lang.IllegalArgumentException: expression cannot be null.
E/MethodChannel#com.saltechsystems.couchbase_lite/json(11267): 	at com.couchbase.lite.From.where(From.java:71)
E/MethodChannel#com.saltechsystems.couchbase_lite/json(11267): 	at com.saltechsystems.couchbase_lite.QueryJson.inflateWhere(QueryJson.java:270)
E/MethodChannel#com.saltechsystems.couchbase_lite/json(11267): 	at com.saltechsystems.couchbase_lite.QueryJson.toCouchbaseQuery(QueryJson.java:64)
E/MethodChannel#com.saltechsystems.couchbase_lite/json(11267): 	at com.saltechsystems.couchbase_lite.CouchbaseLitePlugin$JSONCallHandler.onMethodCall(CouchbaseLitePlugin.java:294)`

it seems there are no implementations of these functions in QueryJson.java

**Comment by bawelter** [comment]
I have this implemented but haven’t pushed the code to the repo.  I will try to upload this to the repo at least so you can use it.  There are quite a bit of additions which will be coming in the next release but just be aware there are some breaking changes.

**Comment by moodstubos** [comment]
Hi @bawelter 
No problem! Thanks a lot for your work.

Many greetings from Germany.

**Comment by bawelter** [comment]
I have a beta branch which should have the changes you need plus some more.  Remember there are some breaking so just let me know if you have any difficulties.
