### ISSUE TITLE
Crash when initiating database, but only with published app

### ISSUE THREAD

**Issue by DustyLamp** [SaltechSystems/couchbase_lite#19]
**Describe the bug**
Flutter application that has been published on Google Play crashes when initializing database

**To Reproduce**
1. Release application to the play store with 
`_database = await Database.initWithName(_dbName);`
2. Run the application with logcat open in Android Studio
3. Watch the application crash and burn
4. See error:

> E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoSuchMethodError: no static method "Lcom/couchbase/litecore/C4Log;.logCallback(Ljava/lang/String;ILjava/lang/String;)V"
>         at com.couchbase.litecore.C4Log.setCallbackLevel(Native Method)
>         at com.couchbase.a.ar.<init>(Unknown Source:23)
>         at com.couchbase.a.a.<clinit>(Unknown Source:5)
>         at com.b.a.a.b(Unknown Source:8)
>         at com.b.a.c$a.onMethodCall(Unknown Source:1043)
>         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
>         at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:59)
>         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:6)
>         at android.os.MessageQueue.nativePollOnce(Native Method)
>         at android.os.MessageQueue.next(MessageQueue.java:325)
>         at android.os.Looper.loop(Looper.java:142)
>         at android.app.ActivityThread.main(ActivityThread.java:6944)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7 Edge and Samsung Galaxy S7
 - OS: Android 8.0.0

**Additional context**
I'm using the current beta version of couchbase_lite

I believe the crash occurs while initiating the database as this starts, but never succeeds.

This was originally crashing while testing apks (not during debug) with an application that I created using an older version of flutter. I ported it over to the current version of flutter and the crashes went away during testing, but not in production.

I can't reproduce it in debug, but it reliably occurs in production every time.

**Comment by DustyLamp** [comment]
Might be related to minification or proguard - checking now.

**Comment by bawelter** [comment]
I have a proguard script which is compatible with couchbase.  When I get a chance I’ll post it on here.  But yes this is a proguard issue and you have to exclude certain libraries from minification.

**Comment by bawelter** [comment]
This should work for you.

```
## Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }

# Okio
-keep class sun.misc.Unsafe { *; }
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-dontwarn okio.**

# Couchbase
-keep public class com.couchbase.lite.** { *; }
-dontwarn com.couchbase.lite.**
-keep public class com.couchbase.litecore.** { *; }
-dontwarn com.couchbase.litecore.**
```

**Comment by DustyLamp** [comment]
Thanks for this @bawelter - it worked originally, but now I'm having similar issues again with my releases:

> 2019-10-20 19:36:11.209 17627-17627/? D/CouchBaseLite: initDatabaseWithName: Started Database Initiation
> 2019-10-20 19:36:11.218 3667-5428/? D/CustomFrequencyManagerService: FrequencyrequestList.getNextMaxCPUCoreRequest, index: 3
> 2019-10-20 19:36:11.220 17627-17627/? E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoSuchMethodError: no static method "Lcom/couchbase/litecore/C4Log;.logCallback(Ljava/lang/String;ILjava/lang/String;)V"
>         at com.couchbase.litecore.C4Log.setCallbackLevel(Native Method)
>         at d.a.a.sa.<init>(Unknown Source:23)
>         at d.a.a.e.<clinit>(Unknown Source:5)
>         at d.e.a.a.g(Unknown Source:15)
>         at d.e.a.d$a.onMethodCall(Unknown Source:1035)
>         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
>         at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:57)
>         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
>         at android.os.MessageQueue.nativePollOnce(Native Method)
>         at android.os.MessageQueue.next(MessageQueue.java:325)
>         at android.os.Looper.loop(Looper.java:142)
>         at android.app.ActivityThread.main(ActivityThread.java:6944)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
> 2019-10-20 19:36:11.220 17627-17627/? A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).

I've commented out proguard and minifying. Here's my build.gradle file:

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')

if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "<MY APP ID WAS HERE>"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    
    buildTypes {
        release {
            signingConfig signingConfigs.release

            // minifyEnabled false
            // useProguard false

            // proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
}


```

Since last time my gradle.properties have been updated too. android.enableR8=true

```
android.enableJetifier=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx1536M

android.enableR8=true

```
Also updated gradle:

```
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by DustyLamp** [comment]
Ok, looks like the following was causing the issue in gradle.properties:

`android.enabledR8=true`

**Comment by bawelter** [comment]
I’m going to close this issue since it’s a project configuration issue.
