### ISSUE TITLE
Create indexes

### ISSUE THREAD

**Issue by Geparder** [SaltechSystems/couchbase_lite#21]
https://docs.couchbase.com/couchbase-lite/2.0/java.html#indexing

**Comment by matsunanaro** [comment]
I'm thinking about implementing this feature for non full text indexes. But before staring, I'd like to know if there is already any work under development.

**Comment by bawelter** [comment]
No, this has not been started.  You are more than welcome to fork the project and do a pull request when you're done.  As long as it is clean code and has been tested it'll get accepted.

**Comment by matsunanaro** [comment]
OK. I'll start implementing it. But it may take some time tough. :-)
