### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by SwapnilDhotre** [SaltechSystems/couchbase_lite#23]
I have Xcode 11 installed running app from flutter on iOS simulator gives issue such module compiled by Swift 5.0.1 cannot be imported by Swift 5.1. Even though changing from swift version from Build Setting could not solve problem. 

`/Users/swapnil_dhotre/SwapnilDhotre/Android/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/couchbase_lite-2.5.1+8/ios/Classes/CBManager.swift:10:8: error: module compiled with Swift 5.0.1 cannot be imported by the Swift 4.2.1 compiler: /Users/swapnil_dhotre/SwapnilDhotre/Github/flutter-cmms/ios/Pods/CouchbaseLite-Swift/iOS/CouchbaseLiteSwift.framework/Modules/CouchbaseLiteSwift.swiftmodule/x86_64.swiftmodule
    import CouchbaseLiteSwift`

**Comment by bawelter** [comment]
This is an issue which couchbase lite Swift has.  One option you have until they get it pushed out (shouldn’t be long) is to compile it yourself on the newer compiler and replace the framework files with the new ones.  https://github.com/couchbase/couchbase-lite-ios

**Comment by bawelter** [comment]
Actually this is a previous issue.  I will be pushing a major update soon which will resolve this but it is a breaking change as far as some syntax changes go.
