### ISSUE TITLE
flutter app does not start for iOS build due to: couchbase_lite does not specify a Swift version

### ISSUE THREAD

**Issue by vals-productions** [SaltechSystems/couchbase_lite#39]
I'm getting the following message upon project startup:

 Installing CouchbaseLite (2.7.1)
      > Copying CouchbaseLite from `/Users/developer/Library/Caches/CocoaPods/Pods/Release/CouchbaseLite/2.7.1-cccdd` to `Pods/CouchbaseLite`

 Installing CouchbaseLite-Swift (2.7.1)
      > Copying CouchbaseLite-Swift from `/Users/developer/Library/Caches/CocoaPods/Pods/Release/CouchbaseLite-Swift/2.7.1-02012` to `Pods/CouchbaseLite-Swift`

 Installing couchbase_lite **(0.0.1)** ????

 `couchbase_lite` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

I configured the project according to Install help page.
```
dependencies:
  ...
  couchbase_lite: ^2.7.1
```

I did not even implement anything yet. Just added a dependency.

Android project starts up without issues.

**Comment by bawelter** [comment]
Make sure you created your flutter project with the swift option and let me know how that works.  Should be able to remove the iOS directory and run ‘’’flutter create -i swift package_name’’’ if you don’t have a really complicated setup for iOS.

**Comment by vals-productions** [comment]
This helped, thanks!
