### ISSUE TITLE
Adding documents and then syncing via channel filtering

### ISSUE THREAD

**Issue by ervijjusty** [SaltechSystems/couchbase_lite#40]
Is there any to use the filter on a pull method.

pull.Filter=“sync_gateway/bychannel”; // Added for filtering
pull.Channels = channel; // Added for filtering

push.Continuous = true;
pull.Continuous = true;

push.Start();
pull.Start();

**Comment by bawelter** [comment]
No there is not currently

**Comment by bawelter** [comment]
v2.7.5+6 has this in it
