### ISSUE TITLE
Add channels support for ReplicatorConfiguration

### ISSUE THREAD

**Issue by galunecandrey** [SaltechSystems/couchbase_lite#63]
Hello! First of all, thank you for your work! We are faced with the critical need to use channels in ReplicatorConfiguration. Could you give this time and add support?

**Comment by bawelter** [comment]
I will see what I can do to get the iOS part of the integration done.  Note that the push and pull filtering with this solution is limited so it may not do everything needed if you need filtering with this as well.

**Comment by bawelter** [comment]
v2.7.1+6 has this in it

**Comment by galunecandrey** [comment]
Thank you for help!
