### ISSUE TITLE
Database encryption

### ISSUE THREAD

**Issue by oliver92** [SaltechSystems/couchbase_lite#80]
Are you guys planning on adding the ability to encrypt the local file of the database? I just read the docs for Couchbase Lite Android and Swift, they both support it. 

Here are the links:
https://docs.couchbase.com/couchbase-lite/current/android/learn/java-android-database.html#database-encryption
https://docs.couchbase.com/couchbase-lite/current/swift/learn/swift-database.html#database-encryption

In both cases the encryption is set in the DatabaseConfiguration when creating the database. So perhaps you can add a way for us to set this configuration through Flutter?

Im also open to making a PR for this...

Thank you,
Oliver

**Comment by bawelter** [comment]
This is an enterprise edition feature and we use the community edition.  So to do this you would need to change to the enterprise edition libraries and we would need to keep the changes separate from the master branch.

**Comment by oliver92** [comment]
Oh, i see, i didn't realize deferent libraries are needed. Thank you for the answer. Oliver
