### ISSUE TITLE
Replicator looses connection after 2 1/2 Minutes with error 'Error: Websocket connection closed by peer'

### ISSUE THREAD

**Issue by josefwilhelm** [SaltechSystems/couchbase_lite#87]
**Describe the bug**
Replicator looses connection after 2 1/2 Minutes with error 'Error: Websocket connection closed by peer'

Replicator status goes to  ReplicatorActivityLevel.stopped and stays there. 

This problem only exists with version 2.8.1
With previous versions the Replicator reconnected without problems. 

Only tested on Android so far

*Edit

Here are some code snippets

This is how I start the replication

```dart
_database = await Database.initWithName(databaseName);
final couchbaseUrl = 'wss://$host/fieldforce_$client';
final config = ReplicatorConfiguration(_database, couchbaseUrl);
config.replicatorType = ReplicatorType.pushAndPull;
config.continuous = true;
config.authenticator =
          SessionAuthenticator(store.state.appSettingsState.syncToken);
_replicator = Replicator(config);
await _replicator.start();
```

This is the error in the client when I lose the connection after 150 seconds
The 1001 is described in the documentation as 1001: DNS resolution error. But unsure why it looses the connection after a certain time. 
It works fine with version 2.7.1

```
E/CouchbaseLite/REPLICATOR( 9062): {Repl#1} Got LiteCore error: WebSocket error 1001 "WebSocket connection closed by peer" 
I/flutter ( 9062): 2021-05-21T11:10:53.448496 ⛔ CouchbaseClient - Error: WebSocket connection closed by peer
I/flutter ( 9062): (CouchbaseLite Android v2.8.1-1 (CE/release, Commit/a9c0287d1e@c65a5127e818 Core/2.8.1 (1) at 2020-10-31T20:38:30.143Z) on Java; Android 10; SM-A515F)
```

These are the SyncGateway log from starting the session and when the disconnect happens. Seems normal

```
2021-05-21T09:21:11.742966501Z 2021-05-21T09:21:11.741Z [INF] WS: c:#8840 Start BLIP/Websocket handler
2021-05-21T09:21:11.743003839Z 2021-05-21T09:21:11.741Z [DBG] WSFrame+: c:#8840 Sender starting
2021-05-21T09:21:11.771464594Z 2021-05-21T09:21:11.769Z [DBG] WSFrame+: c:#8840 Received frame: MSG#1 (flags=       0, length=62)
2021-05-21T09:21:11.771497207Z 2021-05-21T09:21:11.769Z [DBG] WS+: c:#8840 Incoming BLIP Request: MSG#1
```

```
2021-05-21T09:23:41.813368847Z 2021-05-21T09:23:41.811Z [DBG] WSFrame+: c:#8840 receiveLoop stopped
2021-05-21T09:23:41.813450268Z 2021-05-21T09:23:41.811Z [DBG] WSFrame+: c:#8840 parseLoop stopped
2021-05-21T09:23:41.813461064Z 2021-05-21T09:23:41.811Z [DBG] WSFrame+: c:#8840 Sender stopped
2021-05-21T09:23:41.863769406Z 2021-05-21T09:23:41.862Z [INF] HTTP: c:[e898402] #8840: --> BLIP+WebSocket connection closed
2021-05-21T09:23:41.863819544Z 2021-05-21T09:23:41.862Z [DBG] Changes+: Notifying to check for _changes feed termination
2021-05-21T09:23:41.863826558Z 2021-05-21T09:23:41.862Z [DBG] Changes+: No new changes to send to change listener. Waiting for "Fieldforce_01"'s count to pass 60
2021-05-21T09:23:41.863830944Z 2021-05-21T09:23:41.862Z [INF] Changes: c:[e898402] MultiChangesFeed done (to joe.wilhelm2)
2021-05-21T09:23:41.863834890Z 2021-05-21T09:23:41.862Z [DBG] SyncMsg+: c:[e898402] #2: Type:subChanges --> Time:2m30.067421298s
```

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)
    ! Error: iPhone is not paired with your computer. To use iPhone with Xcode,
      unlock it and choose to trust this computer when prompted. (code -9)

• No issues found!
```

**Comment by function1983** [comment]
Maybe some `replicator/syngateway logs`, `flutter doctor` output, and `code snippet` would help us debug your problem better? I have 2.8.1 on a production system running rock solid for last couple of months.

**Comment by e-adrien** [comment]
Do you use wss for the connection ?
I have the same issue on Android (iOS is fine) with the 2.8.1 version.
The Couchbase Lite library doesn't trust the SSL certificate of the server.
I don't have any issue if I downgrade the dependency in android/build.gradle to 2.7.1.

(Edit) Sorry, I don't think it's related to your problem as you lost the connection after some time.
I should have read it twice.

**Comment by josefwilhelm** [comment]
I updated my original post with some code snippets and logs. 

@function1983 how to I get more replicator logs in Flutter sdk? I can't find a way to enable a different log level. Thanks

**Comment by function1983** [comment]
@josefwilhelm Is your SG behind any kind of proxy? Based on my observation, the client will automatically try to reconnect to SG after unexpected disconnections, which happens quite frequent in a mobile environment. If you don't see that behavior in either of the logs then the client must have been willingly disconnected itself from SG.

Add this to your existing code to get the client's error message.
```
_replicator.addChangeListener((ReplicatorChange event) {
        if (event.status.error != null) {
          logger.w("Replicator Error: " + event.status.error);
        }
        logger.d(event.status.activity.toString()); //in case you want full debug
      });
```

**Comment by bawelter** [comment]
Looks like issue was resolved.  Also upgraded sdks so this may have been the issue.
