### ISSUE TITLE
Out of date dependencies

### ISSUE THREAD

**Issue by mehrdad-shokri** [SaltechSystems/couchbase_lite#90]
**Describe the bug**
Unmached peer dependencies with other installed libraries

**To Reproduce**
1. Install couchbase_lit
2. Install another library like flutter_flavorizr v2 flutter_cache_manager v3
3. Dependency conflict

**Expected behavior**
Install as expected

**Screenshots**
None  

**Additional context**
Can you update dependencies of this library specifically ``encrypt`` ``crypto`` ``uuid`` ``pedantic`` so that we can install latest versions of other libraries too?

**Comment by mehrdad-shokri** [comment]
I think choosing Couchbase as my flutter app storage was the wrong decision. ALthough real-time updates seem attractive at first, but, making the whole service dependant on Couchbase was a wrong move in general. You are tightly bound to Couchbase in both your mobile app and backend. coupling mobile app with a dependency which isn't an official SDK and doesn't get updated in 6 months makes the whole codebase obsolete. can't update other dependencies because of the out of date dependencies that this lib depends on.

**Comment by function1983** [comment]
Hi, I think every technology stack will have this very same problem you are talking about.

You will find in the [PRs](https://github.com/SaltechSystems/couchbase_lite/pull/86) other put up some of the update path and with a little work here and there you will get this repository working with the new flutter and dart. It took me a day or two and my project is running fine with 20+ null-safety dependencies. I know that it might be frustrating but the guy share his work for free and asking nothing in return. Everything you need is there in the code base and the PRs.

Ask for help if you need any.

**Comment by bawelter** [comment]
@function1983 I merged your changes in but the cd pipeline broke on me so changes will be in master but not published yet.

**Comment by bawelter** [comment]
@mehrdad-shokri good callout.  If I am not able to keep this current I will try to get some more admins on board to help.  I do rely on this being an open source solution so if there is an issue please feel free to fix it and create a PR.  Have a great day!

**Comment by bawelter** [comment]
Upgraded this and did a prerelease of the nullsafety version
