### ISSUE TITLE
Flutter Web Support

### ISSUE THREAD

**Issue by edityomurti** [SaltechSystems/couchbase_lite#95]
What would it take to use this lib on a Flutter Web app?

**Comment by bawelter** [comment]
There isn't an sdk that supports this which is the problem. I don't know what a web platform integration for this would look like / if it can be done with out writing a native solution in dart.

**Comment by bawelter** [comment]
Would look at this solution they might be closer https://github.com/Rudiksz/couchbase_lite_dart
